/**
 * postpartumData.js
 * Comprehensive clinical references, recovery milestones, lochia staging,
 * "Can I do this yet?" guidance, and educational micro-reads for the 4th Trimester.
 */

export const POSTPARTUM_PHASES = Object.freeze({
  IMMEDIATE: {
    key: 'immediate',
    name: 'Immediate Recovery',
    range: 'Days 1 – 7',
    description: 'Initial acute physiological healing, milk coming in, dramatic hormonal shift, and lochia rubra.',
    primaryFocus: ['Rest & horizontal healing', 'Lochia monitoring', 'Colostrum & lactation onset', 'Perineal / C-section care'],
  },
  EARLY: {
    key: 'early',
    name: 'Early Healing',
    range: 'Days 8 – 42 (Weeks 2 – 6)',
    description: 'Tissue rebuilding, lochia serosa transitions, emotional recalibration, and emerging newborn rhythm.',
    primaryFocus: ['Pelvic floor rest & breath', 'Baby blues vs PPD screening', 'Incision scar settling', 'Gentle walking'],
  },
  EXTENDED: {
    key: 'extended',
    name: 'Extended 4th Trimester',
    range: 'Weeks 7 – 24 (Months 2 – 6)',
    description: 'Core rehabilitation, hormonal stabilization, sleep debt navigation, and pediatric milestones.',
    primaryFocus: ['Postnatal clinical clearance', 'Progressive core strength', 'Maternal mental stamina', 'Feeding rhythm'],
  },
  TRANSITION: {
    key: 'transition',
    name: 'Transition to Motherhood',
    range: 'Months 6 – 12',
    description: 'Long-term tissue restoration, possible return of menstrual cycle, complementary feeding, and maternal identity.',
    primaryFocus: ['Joint & ligament stabilization', 'Weaning or sustained feeding', 'Emotional integration', 'Long-term vitality'],
  },
});

export const LOCHIA_STAGES = Object.freeze({
  RUBRA: {
    stage: 'Lochia Rubra',
    days: 'Days 1 – 4',
    color: 'Dark Red / Crimson',
    expectedFlow: 'Moderate to heavy with small dime-sized clots.',
    guidance: 'Expected right after birth as the placental site contracts. Frequent pad changes and horizontal rest help prevent surges.',
    redFlags: 'Soaking more than one large pad per hour for 2+ consecutive hours, or passing clots larger than a golf ball.',
  },
  SEROSA: {
    stage: 'Lochia Serosa',
    days: 'Days 5 – 10 (up to Day 14)',
    color: 'Pinkish / Brown / Watery',
    expectedFlow: 'Lighter consistency, less active blood.',
    guidance: 'Shows active tissue healing. If bleeding suddenly returns to bright red heavy flow, your body is signalling for you to slow down physical activity.',
    redFlags: 'Foul-smelling discharge, sudden fever, or sudden return of heavy bright red bleeding with cramping.',
  },
  ALBA: {
    stage: 'Lochia Alba',
    days: 'Weeks 2 – 6',
    color: 'Yellowish-white / Cream',
    expectedFlow: 'Scant discharge consisting of mucus and healing tissue.',
    guidance: 'The final phase of uterine lining renewal. Light panty liners are usually sufficient.',
    redFlags: 'Persistent burning with urination, pelvic pain, or discharge accompanied by fever (>100.4°F / 38°C).',
  },
});

export const RECOVERY_MILESTONES = Object.freeze([
  {
    day: 1,
    title: 'Welcome Home & The Golden Rest',
    vaginal: 'Focus on horizontal rest, ice packs/witch hazel for perineal comfort, and gentle hydration.',
    cesarean: 'Prioritize wound splinting when coughing/laughing, scheduled analgesia, and slow assisted walking.',
  },
  {
    day: 3,
    title: 'Hormonal Reset & Milk Transition',
    vaginal: 'Dramatic estrogen/progesterone drop. Tearfulness ("Baby Blues") is completely physiological. Warm showers help breast engorgement.',
    cesarean: 'Incision begins superficial sealing. Gas pains can peak today; gentle walking and hydration help mobility.',
  },
  {
    day: 7,
    title: 'First Week Completed',
    vaginal: 'Lochia transitions from dark red to pink/brown (Serosa). Pelvic heaviness should be decreasing with rest.',
    cesarean: 'First incision check with provider. Steri-strips or glue may begin peeling; keep clean and dry without scrubbing.',
  },
  {
    day: 14,
    title: 'Two-Week Wellbeing & Mood Checkpoint',
    vaginal: 'Perineal stitches usually starting to dissolve. Two-week emotional check-in (EPDS screening checkpoint).',
    cesarean: 'Incision tenderness shifting from sharp to dull ache. Two-week emotional check-in (EPDS screening checkpoint).',
  },
  {
    day: 28,
    title: 'One Month Milestone',
    vaginal: 'Lochia shifting toward scant white/yellow (Alba). Gentle diaphragmatic breathing and deep core reconnection.',
    cesarean: 'Subsurface incision tissue continues remodeling. Light walking can be extended; avoid lifting heavier than your baby.',
  },
  {
    day: 42,
    title: 'Six-Week Postnatal Clinical Review',
    vaginal: 'Official OB/GYN or midwife comprehensive exam: pelvic floor tone, cervix closure, contraception counseling, mental health.',
    cesarean: 'Comprehensive checkup: deep abdominal scar healing, diastasis recti assessment, safe return to gradual fitness clearance.',
  },
]);

export const CAN_I_DO_THIS_YET = Object.freeze([
  {
    activity: 'Exercise',
    icon: 'fitness',
    category: 'Movement',
    timeline: 'Vaginal: Gentle walks right away, core/light rehab 2–4w, high impact 6–12w. C-Section: Walking right away, formal exercise after 6–8w clearance.',
    recommendation: 'Walking and diaphragmatic breathing can begin immediately. Hold off on running, jumping, crunches, and heavy weights until your 6-week pelvic floor and incision check.',
  },
  {
    activity: 'Driving',
    icon: 'car',
    category: 'Mobility',
    timeline: 'Vaginal: Usually 1–2 weeks once pain-free. C-Section: Typically 2–3 weeks once off narcotic pain medication and able to perform an emergency brake stop without incision hesitation.',
    recommendation: 'Test your ability to stomp the brake firmly while stationary. If it causes sharp pain or hesitation, wait a few more days.',
  },
  {
    activity: 'Lifting',
    icon: 'luggage',
    category: 'Daily Life',
    timeline: 'First 6 weeks: Never lift anything heavier than your baby in their car seat (approx 10–15 lbs / 5–7 kg).',
    recommendation: 'Excessive intra-abdominal pressure strains healing perineal tissue, C-section fascial repairs, and your pelvic floor.',
  },
  {
    activity: 'Sex & Intimacy',
    icon: 'heart',
    category: 'Intimacy',
    timeline: 'Standard clinical guideline: Wait until lochia has completely stopped and after your 6-week postnatal clearance.',
    recommendation: 'Early intercourse introduces infection risk to the placental wound site. Estrogen drops also cause vaginal dryness; lubrications and zero pressure are essential.',
  },
  {
    activity: 'Swimming & Baths',
    icon: 'pool',
    category: 'Hygiene',
    timeline: 'Showers: Immediate. Submerged baths / pools / hot tubs: Wait until bleeding has stopped and incision/perineum is fully closed (typically 4–6 weeks).',
    recommendation: 'Submerging in water while your cervix is still slightly open increases uterine infection risk.',
  },
  {
    activity: 'Sleeping on Stomach',
    icon: 'bed',
    category: 'Sleep',
    timeline: 'Vaginal: Whenever comfortable. C-Section: Once incision pressure is tolerable (often 2–4 weeks).',
    recommendation: 'If breastfeeding, sleeping on your stomach may put excessive pressure on full breasts, leading to plugged ducts. A pillow under the hips helps.',
  },
]);

export const CONTEXTUAL_READS = Object.freeze([
  {
    id: 'pr_01',
    title: 'The Great Hormone Plunge (Days 3–5)',
    topic: 'Mental Health',
    readingTime: '60 sec',
    trigger: 'day <= 7',
    summary: 'Why sudden crying and overwhelming tenderness are physiological hormonal crashes, not personal failure.',
  },
  {
    id: 'pr_02',
    title: 'Lochia Colors: When to Rest vs When to Call',
    topic: 'Physical Recovery',
    readingTime: '90 sec',
    trigger: 'bleeding',
    summary: 'How your bleeding shifts from Rubra to Serosa, and what your body is telling you when red blood returns.',
  },
  {
    id: 'pr_03',
    title: 'C-Section Scar Care: The First 3 Weeks',
    topic: 'Incision Healing',
    readingTime: '75 sec',
    trigger: 'cesarean',
    summary: 'Keep it clean, keep it dry, and why gentle abdominal splinting protects your fascial layer.',
  },
  {
    id: 'pr_04',
    title: 'Sore Nipples vs Engorgement: Immediate Relief',
    topic: 'Lactation',
    readingTime: '60 sec',
    trigger: 'breast',
    summary: 'Colostrum to mature milk transition, reverse pressure softening, and correcting shallow latches.',
  },
  {
    id: 'pr_05',
    title: 'The 2-Week Postpartum Mood Screening (EPDS)',
    topic: 'Clinical Care',
    readingTime: '90 sec',
    trigger: 'day >= 14',
    summary: 'Understanding the validated 10-question tool used worldwide to support new mothers with postpartum anxiety and depression.',
  },
]);

export const LACTATION_SAFETY_RULES = Object.freeze([
  {
    keywords: ['ibuprofen', 'advil', 'motrin', 'brufen'],
    query: 'Ibuprofen',
    status: 'safe',
    badge: 'Safe While Nursing',
    colorHex: '#0D9488',
    summary: 'Ibuprofen is the preferred first-line pain and anti-inflammatory relief during lactation.',
    reasoning: 'Extremely low excretion into breast milk (less than 1% of maternal dose). It is safe for both vaginal tearing and C-section incision recovery.',
    safeAlternative: 'Take with food or a glass of water. Paracetamol is also a safe alternative.',
    docQuestion: 'What is the recommended dosing interval for my postpartum recovery pain?',
  },
  {
    keywords: ['paracetamol', 'acetaminophen', 'tylenol', 'crocin', 'panadol'],
    query: 'Paracetamol / Acetaminophen',
    status: 'safe',
    badge: 'Safe While Nursing',
    colorHex: '#0D9488',
    summary: 'Paracetamol is safe and compatible with breastfeeding at standard therapeutic doses.',
    reasoning: 'Only very small amounts pass into breast milk, far below therapeutic doses given directly to infants.',
    safeAlternative: 'Can be alternated with Ibuprofen under medical guidance for multi-modal postpartum analgesia.',
    docQuestion: 'Can I alternate Paracetamol with Ibuprofen for post-delivery discomfort?',
  },
  {
    keywords: ['aspirin', 'disprin', 'ecotrin', 'bayer'],
    query: 'Aspirin',
    status: 'avoid',
    badge: 'Avoid While Nursing',
    colorHex: '#DD0D22',
    summary: 'Standard or high-dose aspirin should be avoided while breastfeeding.',
    reasoning: 'Salicylates pass into breast milk and carry a theoretical risk of metabolic acidosis, platelet dysfunction, and Reye’s syndrome in nursing infants.',
    safeAlternative: 'Use Ibuprofen or Paracetamol for postpartum aches, fever, or pain instead.',
    docQuestion: 'If prescribed low-dose aspirin for cardiovascular indications, is a safer alternative available while nursing?',
  },
  {
    keywords: ['sudafed', 'pseudoephedrine', 'decongestant', 'cold medicine', 'sinus'],
    query: 'Sudafed / Pseudoephedrine',
    status: 'avoid',
    badge: 'Avoid / Reduces Supply',
    colorHex: '#DD0D22',
    summary: 'Avoid oral pseudoephedrine if you want to protect your breast milk supply.',
    reasoning: 'Pseudoephedrine acts on prolactin receptors and has been shown to reduce milk supply by up to 24% after even a single dose.',
    safeAlternative: 'Use saline nasal sprays, facial steam inhalation, honey with lemon, or nasal steroid sprays instead.',
    docQuestion: 'What non-decongestant cold remedy will not decrease my milk supply?',
  },
  {
    keywords: ['fenugreek', 'methi', 'galactagogue', 'milk tea'],
    query: 'Fenugreek',
    status: 'caution',
    badge: 'Use Caution / Monitor',
    colorHex: '#D97706',
    summary: 'Use caution with Fenugreek supplements. It can cause infant and maternal digestive distress.',
    reasoning: 'While popular for increasing supply, fenugreek frequently causes gas, loose green stools, and cramps in infants, and can interfere with maternal thyroid or blood sugar balance.',
    safeAlternative: 'Prioritize frequent milk removal (skin-to-skin, demand feeding, power pumping), hydration, oats, and moringa instead.',
    docQuestion: 'Would an evaluation by an IBCLC lactation consultant help my milk supply before taking herbal supplements?',
  },
  {
    keywords: ['coffee', 'caffeine', 'espresso', 'cappuccino', 'latte', 'energy drink'],
    query: 'Coffee / Caffeine',
    status: 'caution',
    badge: 'Moderate (1-2 Cups)',
    colorHex: '#D97706',
    summary: 'Moderate caffeine (up to 200–300 mg / about 2 standard cups) is considered safe while nursing.',
    reasoning: 'Under 1% of caffeine reaches breast milk, but newborn infants metabolize caffeine very slowly. Excess intake (>300mg) may cause infant fussiness and wakefulness.',
    safeAlternative: 'Have your cup right after a nursing session so maternal peak blood levels drop before the next feed. Chicory or decaf are great alternatives.',
    docQuestion: 'Does my baby show any signs of caffeine sensitivity, especially during the newborn weeks?',
  },
  {
    keywords: ['alcohol', 'wine', 'beer', 'cocktail', 'champagne'],
    query: 'Alcohol / Wine / Beer',
    status: 'caution',
    badge: 'Timing Essential',
    colorHex: '#D97706',
    summary: 'Alcohol passes into milk at blood levels. Wait at least 2 hours per standard drink before nursing.',
    reasoning: 'Alcohol impairs the milk ejection (letdown) reflex and can alter infant sleep patterns. Pumping and dumping does not speed elimination—only time clears alcohol from your bloodstream and milk.',
    safeAlternative: 'Nurse your baby immediately before having a single standard drink, or offer previously expressed milk.',
    docQuestion: 'What is the safest guidance on social alcohol timing for my feeding routine?',
  },
  {
    keywords: ['peppermint', 'sage', 'spearmint'],
    query: 'Peppermint & Sage',
    status: 'caution',
    badge: 'May Lower Supply',
    colorHex: '#D97706',
    summary: 'High culinary or concentrated herbal amounts of peppermint and sage can decrease breast milk production.',
    reasoning: 'Menthol and thujone compounds can inhibit lactation and are clinically used intentionally when mothers want to wean or suppress milk.',
    safeAlternative: 'Chamomile, ginger, rooibos, or fruit teas are gentle and supply-friendly.',
    docQuestion: 'Could my consumption of herbal teas be affecting my daily pumping output?',
  },
  {
    keywords: ['amoxicillin', 'augmentin', 'antibiotic', 'keflex', 'cephalexin'],
    query: 'Amoxicillin / Postpartum Antibiotics',
    status: 'safe',
    badge: 'Safe With Guidance',
    colorHex: '#0D9488',
    summary: 'Standard penicillins and cephalosporins are safe and first-line for postpartum infections and mastitis.',
    reasoning: 'Negligible milk transfer. Very safe for the infant, though baby may occasionally have looser stools or temporary mild diaper rash.',
    safeAlternative: 'Take prescribed infant probiotics or maternal probiotics if your baby experiences digestive sensitivity.',
    docQuestion: 'Should I give infant probiotics while completing my prescribed antibiotic course?',
  },
  {
    keywords: ['benadryl', 'diphenhydramine', 'antihistamine', 'allergy'],
    query: 'Benadryl / Diphenhydramine',
    status: 'caution',
    badge: 'Prefer Non-Drowsy',
    colorHex: '#D97706',
    summary: 'Sedating antihistamines can cause maternal and infant drowsiness and may decrease milk production.',
    reasoning: 'First-generation antihistamines cross into milk and also inhibit prolactin release with repeated doses.',
    safeAlternative: 'Non-sedating second-generation antihistamines like Loratadine (Claritin) or Cetirizine (Zyrtec) are preferred during lactation.',
    docQuestion: 'Can I switch to Loratadine or Cetirizine for my allergy symptoms?',
  },
  {
    keywords: ['sushi', 'raw fish', 'salmon', 'tuna', 'sashimi'],
    query: 'Sushi & Fish While Nursing',
    status: 'safe',
    badge: 'Safe (Watch Mercury)',
    colorHex: '#0D9488',
    summary: 'Clean, fresh sushi is safe while breastfeeding! Food poisoning bacteria do not pass into breast milk.',
    reasoning: 'Unlike pregnancy, Listeria does not cross into breast milk. Simply avoid high-mercury apex predators (swordfish, shark, bigeye tuna). Cooked or raw salmon is rich in DHA which enriches breast milk.',
    safeAlternative: 'Salmon, shrimp, pollack, and canned light tuna are excellent low-mercury, high-DHA choices.',
    docQuestion: 'What are the best DHA-rich fish options for enriching breast milk?',
  },
  {
    keywords: ['retinol', 'retinoid', 'tretinoin', 'skincare'],
    query: 'Retinol / Topical Retinoids',
    status: 'caution',
    badge: 'Keep Away From Chest',
    colorHex: '#D97706',
    summary: 'Topical facial retinol has minimal systemic absorption, but must never touch breasts or be ingested by baby.',
    reasoning: 'Systemic absorption from facial creams is low, but oral retinoids (Accutane) are strictly contraindicated. Ensure skin is washed and baby does not rub against treated areas.',
    safeAlternative: 'Bakuchiol, azelaic acid, hyaluronic acid, and niacinamide are gentler, breastfeeding-friendly skincare alternatives.',
    docQuestion: 'Can I safely resume my facial skincare routine while nursing?',
  },
]);

