import 'dart:async';
import 'dart:convert';

import 'package:flutter/foundation.dart';
import 'package:http/http.dart' as http;

import 'api_auth_service.dart';
import 'api_base_url.dart';
import 'auth_storage.dart';

/// The states the backend can return for any card (spec section 27
/// "STANDARD API RESPONSE CONTRACT" and section 4 "FRONTEND STATES EVERY CARD
/// MUST SUPPORT").
///
/// `loading`, `stale` and `offline` are client-side states: the server never
/// sends them, but every card has to be able to render them.
enum ApiState {
  loading,
  ready,
  empty,
  insufficientData,
  restricted,
  error,
  stale,
  offline,
}

ApiState _parseState(String? raw) {
  switch (raw) {
    case 'ready':
      return ApiState.ready;
    case 'empty':
      return ApiState.empty;
    case 'insufficient_data':
    case 'not_enough_data':
      return ApiState.insufficientData;
    case 'restricted':
      return ApiState.restricted;
    case 'error':
      return ApiState.error;
    default:
      return ApiState.error;
  }
}

/// A typed wrapper around one backend response.
///
/// Carries the full contract so a widget can decide what to render without
/// guessing: `state` says which of the eight card states applies, `source`
/// says whether the value was reported by the user, calculated by a rule, or
/// generated by AI, and `version` identifies the calculation behind a number.
@immutable
class ApiResult<T> {
  final T? data;
  final ApiState state;
  final DateTime? lastUpdated;
  final String? source;
  final String? version;
  final Map<String, dynamic>? permissions;
  final String? errorCode;
  final String? errorMessage;
  final Map<String, dynamic>? meta;

  const ApiResult({
    this.data,
    required this.state,
    this.lastUpdated,
    this.source,
    this.version,
    this.permissions,
    this.errorCode,
    this.errorMessage,
    this.meta,
  });

  const ApiResult.loading()
      : data = null,
        state = ApiState.loading,
        lastUpdated = null,
        source = null,
        version = null,
        permissions = null,
        errorCode = null,
        errorMessage = null,
        meta = null;

  const ApiResult.offline({this.data, this.lastUpdated})
      : state = ApiState.offline,
        source = null,
        version = null,
        permissions = null,
        errorCode = 'OFFLINE',
        errorMessage = null,
        meta = null;

  bool get isReady => state == ApiState.ready;
  bool get hasData => data != null && state == ApiState.ready;

  /// True when the card should show a "not enough data yet" treatment rather
  /// than an empty one. The spec keeps these distinct on purpose.
  bool get isInsufficientData => state == ApiState.insufficientData;

  /// True when the information exists but the viewer is not permitted to see
  /// it. Partner surfaces use this to render the restricted treatment.
  bool get isRestricted => state == ApiState.restricted;

  bool get isError => state == ApiState.error;

  /// True when a displayed value came from AI rather than from the user's own
  /// logs or a deterministic rule, so the UI can label it.
  bool get isAiGenerated => source == 'ai';

  ApiResult<R> map<R>(R Function(T value) transform) {
    return ApiResult<R>(
      data: data == null ? null : transform(data as T),
      state: state,
      lastUpdated: lastUpdated,
      source: source,
      version: version,
      permissions: permissions,
      errorCode: errorCode,
      errorMessage: errorMessage,
      meta: meta,
    );
  }
}

/// Shared HTTP client for the spec-aligned `/api/v1` surface.
///
/// One place owns the base URL, the auth header, timeouts, the response
/// contract and error mapping, so every screen behaves the same way.
class ApiContractClient {
  ApiContractClient._();

  static const Duration _timeout = Duration(seconds: 20);

  static String get _base => '${resolveApiBaseUrl()}/api/v1';

  static Map<String, String> _headers({String? idempotencyKey}) {
    final token = AuthStorage.getToken();
    return {
      'Content-Type': 'application/json',
      if (token != null) 'Authorization': 'Bearer $token',
      'Idempotency-Key': ?idempotencyKey,
    };
  }

  /// Guards against a refresh storm: a 401 on the refresh call itself, or
  /// several requests failing at once, must not each start their own refresh.
  static bool _refreshing = false;

  static Future<bool> _tryRefreshSession() async {
    if (_refreshing) return false;
    _refreshing = true;
    try {
      return await ApiAuthService().refreshSession();
    } catch (_) {
      return false;
    } finally {
      _refreshing = false;
    }
  }

  static Future<ApiResult<T>> _send<T>(
    Future<http.Response> Function() request,
    T Function(dynamic data)? parse,
  ) async {
    try {
      var response = await request().timeout(_timeout);

      // An expired access token is recoverable: the refresh token was being
      // stored and never used, so a session that lapsed mid-use turned every
      // request into an error. One retry, and only after a refresh actually
      // succeeds, so a genuinely revoked session still surfaces as 401.
      if (response.statusCode == 401 && !_refreshing) {
        if (await _tryRefreshSession()) {
          response = await request().timeout(_timeout);
        }
      }

      return _decode<T>(response, parse);
    } on TimeoutException {
      return const ApiResult(
        state: ApiState.error,
        errorCode: 'TIMEOUT',
        errorMessage: 'The request timed out. Please try again.',
      );
    } catch (error) {
      // A failed request is treated as offline rather than an error, so cards
      // can show the last known safe state and queue supported writes
      // (spec section 25).
      if (kDebugMode) {
        // The host is worth printing: the usual cause of this branch in
        // development is a base URL the device cannot route to, which is not
        // a connectivity problem and cannot be diagnosed from the UI copy.
        debugPrint('[api] request to ${resolveApiBaseUrl()} failed: $error');
      }
      return const ApiResult(
        state: ApiState.offline,
        errorCode: 'NETWORK_UNAVAILABLE',
        errorMessage: 'Could not reach the server. Showing the last known state.',
      );
    }
  }

  static ApiResult<T> _decode<T>(http.Response response, T Function(dynamic data)? parse) {
    Map<String, dynamic> body;
    try {
      final decoded = jsonDecode(response.body);
      body = decoded is Map<String, dynamic> ? decoded : <String, dynamic>{};
    } catch (_) {
      return ApiResult<T>(
        state: ApiState.error,
        errorCode: 'MALFORMED_RESPONSE',
        errorMessage: 'The server returned an unexpected response.',
      );
    }

    // Routes outside the v1 surface still use the older error shape.
    if (!body.containsKey('state') && body.containsKey('error')) {
      final error = body['error'];
      return ApiResult<T>(
        state: ApiState.error,
        errorCode: error is Map ? error['code']?.toString() : null,
        errorMessage: error is Map ? error['message']?.toString() : error?.toString(),
      );
    }

    final state = _parseState(body['state']?.toString());
    final rawData = body['data'];

    T? parsed;
    if (rawData != null && parse != null) {
      try {
        parsed = parse(rawData);
      } catch (error) {
        if (kDebugMode) {
          debugPrint('[api] failed to parse payload: $error');
        }
        return ApiResult<T>(
          state: ApiState.error,
          errorCode: 'PARSE_FAILED',
          errorMessage: 'The response could not be read.',
        );
      }
    } else if (rawData is T) {
      parsed = rawData;
    }

    return ApiResult<T>(
      data: parsed,
      state: state,
      lastUpdated: body['lastUpdated'] != null ? DateTime.tryParse(body['lastUpdated'].toString()) : null,
      source: body['source']?.toString(),
      version: body['version']?.toString(),
      permissions: body['permissions'] is Map<String, dynamic> ? body['permissions'] as Map<String, dynamic> : null,
      errorCode: body['errorCode']?.toString(),
      errorMessage: body['error'] is Map ? (body['error'] as Map)['message']?.toString() : null,
      meta: body['meta'] is Map<String, dynamic> ? body['meta'] as Map<String, dynamic> : null,
    );
  }

  static Future<ApiResult<T>> get<T>(
    String path, {
    Map<String, String>? query,
    T Function(dynamic data)? parse,
  }) {
    final uri = Uri.parse('$_base$path').replace(
      queryParameters: query == null || query.isEmpty ? null : query,
    );
    return _send<T>(() => http.get(uri, headers: _headers()), parse);
  }

  static Future<ApiResult<T>> post<T>(
    String path, {
    Object? body,
    String? idempotencyKey,
    T Function(dynamic data)? parse,
  }) {
    return _send<T>(
      () => http.post(
        Uri.parse('$_base$path'),
        headers: _headers(idempotencyKey: idempotencyKey),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
    );
  }

  static Future<ApiResult<T>> put<T>(
    String path, {
    Object? body,
    T Function(dynamic data)? parse,
  }) {
    return _send<T>(
      () => http.put(
        Uri.parse('$_base$path'),
        headers: _headers(),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
    );
  }

  static Future<ApiResult<T>> patch<T>(
    String path, {
    Object? body,
    T Function(dynamic data)? parse,
  }) {
    return _send<T>(
      () => http.patch(
        Uri.parse('$_base$path'),
        headers: _headers(),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
    );
  }

  static Future<ApiResult<T>> delete<T>(
    String path, {
    Map<String, String>? query,
    Object? body,
    T Function(dynamic data)? parse,
  }) {
    final uri = Uri.parse('$_base$path').replace(
      queryParameters: query == null || query.isEmpty ? null : query,
    );
    return _send<T>(
      () => http.delete(
        uri,
        headers: _headers(),
        body: body == null ? null : jsonEncode(body),
      ),
      parse,
    );
  }
}

/// Helpers shared by the typed models below.
class ApiParse {
  static List<Map<String, dynamic>> list(dynamic value) {
    if (value is! List) return const [];
    return value.whereType<Map>().map((e) => Map<String, dynamic>.from(e)).toList();
  }

  static Map<String, dynamic> map(dynamic value) {
    if (value is Map) return Map<String, dynamic>.from(value);
    return const {};
  }

  static DateTime? date(dynamic value) {
    if (value == null) return null;
    return DateTime.tryParse(value.toString());
  }

  static String dateOnly(DateTime value) {
    return '${value.year.toString().padLeft(4, '0')}-'
        '${value.month.toString().padLeft(2, '0')}-'
        '${value.day.toString().padLeft(2, '0')}';
  }

  static int? intOrNull(dynamic value) {
    if (value == null) return null;
    if (value is int) return value;
    return int.tryParse(value.toString());
  }

  static double? doubleOrNull(dynamic value) {
    if (value == null) return null;
    if (value is num) return value.toDouble();
    return double.tryParse(value.toString());
  }
}
